<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVWBCZDk\AdminKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVWBCZDk/AdminKernelProdContainer.php') {
    touch(__DIR__.'/ContainerVWBCZDk.legacy');

    return;
}

if (!\class_exists(AdminKernelProdContainer::class, false)) {
    \class_alias(\ContainerVWBCZDk\AdminKernelProdContainer::class, AdminKernelProdContainer::class, false);
}

return new \ContainerVWBCZDk\AdminKernelProdContainer([
    'container.build_hash' => 'VWBCZDk',
    'container.build_id' => '39eb7606',
    'container.build_time' => 1773342340,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVWBCZDk');
