<?php

namespace ContainerVWBCZDk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAttributeTypeService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'PrestaShopBundle\Form\Admin\Sell\Catalog\AttributeType' shared autowired service.
     *
     * @return \PrestaShopBundle\Form\Admin\Sell\Catalog\AttributeType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['PrestaShopBundle\\Form\\Admin\\Sell\\Catalog\\AttributeType'] = new \PrestaShopBundle\Form\Admin\Sell\Catalog\AttributeType(($container->services['Symfony\\Contracts\\Translation\\TranslatorInterface'] ?? self::getTranslatorInterfaceService($container)), ($container->services['PrestaShop\\PrestaShop\\Adapter\\LegacyContext'] ?? self::getLegacyContextService($container))->getLanguages(false), new \PrestaShop\PrestaShop\Core\Form\ChoiceProvider\AttributeGroupChoiceProvider(($container->services['PrestaShopBundle\\Entity\\Repository\\AttributeGroupRepository'] ?? $container->load('getAttributeGroupRepositoryService')), ($container->services['PrestaShop\\PrestaShop\\Adapter\\LegacyContext'] ?? self::getLegacyContextService($container))->getLanguage()->id, ($container->services['.container.private.prestashop.adapter.shop.context'] ??= new \PrestaShop\PrestaShop\Adapter\Shop\Context())->getContextShopID()), ($container->services['PrestaShop\\PrestaShop\\Adapter\\Feature\\MultistoreFeature'] ?? self::getMultistoreFeatureService($container)));
    }
}
