<?php

namespace ContainerByAxbUr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBulkCustomersDeleteProcessorService extends AdminKernelDevDebugContainer
{
    /**
     * Gets the private 'PrestaShop\Module\APIResources\ApiPlatform\Processor\BulkCustomersDeleteProcessor' shared autowired service.
     *
     * @return \PrestaShop\Module\APIResources\ApiPlatform\Processor\BulkCustomersDeleteProcessor
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['PrestaShop\\Module\\APIResources\\ApiPlatform\\Processor\\BulkCustomersDeleteProcessor'] = new \PrestaShop\Module\APIResources\ApiPlatform\Processor\BulkCustomersDeleteProcessor(($container->privates['PrestaShopBundle\\ApiPlatform\\Processor\\CommandProcessor'] ?? $container->load('getCommandProcessorService')));
    }
}
