<?php

namespace ContainerByAxbUr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMultiParameterSetterAdapterService extends AdminKernelDevDebugContainer
{
    /**
     * Gets the private 'PrestaShopBundle\ApiPlatform\OpenApi\Adapter\MultiParameterSetterAdapter' shared autowired service.
     *
     * @return \PrestaShopBundle\ApiPlatform\OpenApi\Adapter\MultiParameterSetterAdapter
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['PrestaShopBundle\\ApiPlatform\\OpenApi\\Adapter\\MultiParameterSetterAdapter'] = new \PrestaShopBundle\ApiPlatform\OpenApi\Adapter\MultiParameterSetterAdapter(($container->privates['api_platform.serializer.mapping.class_metadata_factory'] ?? self::getApiPlatform_Serializer_Mapping_ClassMetadataFactoryService($container)), ($container->privates['PrestaShopBundle\\ApiPlatform\\DomainObjectDetector'] ?? self::getDomainObjectDetectorService($container)));
    }
}
