<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerByAxbUr\AdminKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerByAxbUr/AdminKernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerByAxbUr.legacy');

    return;
}

if (!\class_exists(AdminKernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerByAxbUr\AdminKernelDevDebugContainer::class, AdminKernelDevDebugContainer::class, false);
}

return new \ContainerByAxbUr\AdminKernelDevDebugContainer([
    'container.build_hash' => 'ByAxbUr',
    'container.build_id' => 'b01991c5',
    'container.build_time' => 1773354900,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerByAxbUr');
